name: Build jar and maven project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Use the AdoptOpenJDK distribution
        java-version: '21'     # Set your Java version (e.g., 8, 11, 17)

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Build the project with Maven
    - name: Build with Maven
      run: mvn clean package

    # Step 5: Upload the JAR artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-app-jar
        path: target/*.jar
