name: Build jar and maven project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 3: Build the WAR file
    - name: Build with Maven
      run: mvn clean package

    # Step 4: Set up Tomcat and deploy the WAR
    - name: Set up and deploy to Tomcat
      run: |
        # Download and extract Tomcat
        wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
        tar -xzf apache-tomcat-10.1.6.tar.gz
        mv apache-tomcat-10.1.6 tomcat

        # Copy the WAR file to the webapps directory
        cp target/demo.war tomcat/webapps/

        # Start the Tomcat server
        tomcat/bin/startup.sh   
    
    # Step 5: Upload the JAR artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-app-war
        path: target/*.war
